export const FETCH_POKEMON_LIST_REQUEST = 'pokemons/FETCH_LIST_REQUEST';
export const FETCH_POKEMON_LIST_SUCCESS = 'pokemons/FETCH_LIST_SUCCESS';
export const FETCH_POKEMON_LIST_FAILURE = 'pokemons/FETCH_LIST_FAILURE';

export const FETCH_POKEMON_ONE_REQUEST = 'pokemons/FETCH_ONE_REQUEST';
export const FETCH_POKEMON_ONE_SUCCESS = 'pokemons/FETCH_ONE_SUCCESS';
export const FETCH_POKEMON_ONE_FAILURE = 'pokemons/FETCH_ONE_FAILURE';
